### ISSUE TITLE
upgrading item images

### ISSUE THREAD

**Issue by esperancaJS** [merkatsu/website#102]
What I think we should have in consideration for asking for user images:
- that they will look different in different layouts, so even if we give him a cropping tool we must let him know that on different places it will be "recroped" according to the specific layout
- empowering him to make his images show as much as possible the way he wants them to

My proposed solution:
![img_20150421_091310](https://cloud.githubusercontent.com/assets/1115163/7246490/1ba26ec6-e807-11e4-8330-f1cc018c93ce.jpg)
- focal point: this is where the image will be centered on every layout (no matter the layout ratios for images) 
  ![focal 2](https://cloud.githubusercontent.com/assets/1115163/7246615/92824664-e808-11e4-872e-73519c5c0911.png)
  note: to preserve @mariacovasgrilo's previous design which is super awesome and also to educate the user about the focal point: the focal point could be always centered and as he drags it he sees the image preposition itself. Since the current layout already "auto crops" the image he might "get it" as he repositions it and sees that it is in reality not cropped, just centered in a box that cuts out the excess.
- edit: opens a popup where the user can crop and do any image alteration (as you can see in the image we can use software not managed by us to help with this)
  ![photo editor](https://cloud.githubusercontent.com/assets/1115163/7246624/ac08930e-e808-11e4-8b69-80f22775a630.png)
- cursors and reordering images: when the cursor is over the image it becomes that cursor with the arrows that I think everyone knows it means that the element can be dragged to it's desired position, when the cursor is over the focal point it becomes a hand, just to differentiate. (this last part is the one I'm less sure of)

**Comment by djtanuzzo** [comment]
I honestly don't think that the focal point is necessary. It adds a new layer of complexity to images that has little benefit, given that:
1) People know that when uploading pictures the focal point will be the center.
2) People that crop the image do so with the focal point in the center.

The real problem is that people want control over the way their products are displayed, and if we crop the images without them having control over it, then it will cause frustration where it matters most. Having a focal point does not solve this problem.

If there really is no way for us not crop the user's images, then a notice in the image section is definitely required, something saying: "note that your image may be slightly cropped when displayed in certain places". Additionally a preview of how the cropped image is going to look like could help.

**Comment by esperancaJS** [comment]
Maybe when moving the focal point we could have a section under the image open up with previews of the various ratios we are currently using in the platform

**Comment by esperancaJS** [comment]
here's how [VK](https://vk.com/) does it
![img_20150421_130444](https://cloud.githubusercontent.com/assets/1115163/7250327/fffe228c-e829-11e4-811a-e115449589f9.jpg)

**Comment by djtanuzzo** [comment]
Maybe there is a difficulty in discussing this because we are talking about 2 types of cropping:
1 - Users cropping their images in an editor on merkasu
2 - Merkatsu cropping the user's images when they are displayed

Nr.1 is something that would be nice to have. Not everyone has an image editor or knows how to use one, and we would offer them a simple solution to have a better looking store.

Nr.2 is where the problem lies. Whenever merkatsu crops the user's image without his control, we are introducing possible errors and frustration. Since stores are the backbone of merkatsu, we have to ensure that people have control over them so that they can confidently join the platform.

**Comment by esperancaJS** [comment]
A note for nr. 2 
Merkatsu is planed to scale to a point where we will have user made layouts, but many made by us also.
