### ISSUE TITLE
New Item Pop Up

### ISSUE THREAD

**Issue by mariacovasgrilo** [merkatsu/website#109]
Finally I came up with a layout for the item pop up that should accommodate the edit button and the limit of characters, and reorganizes the whole thing so it looks more organised and clean.

Please let's follow this to the risk and hopefully it will shed new life into the whole platform - I really hope so.

![item popup](https://cloud.githubusercontent.com/assets/10408369/7333561/e11b45c6-eb6b-11e4-8037-cf08e798848f.png)

/\* Outer: 100% Leather: */
font-family: Montserrat-Light;
font-size: 12px;
color: #767075;
line-height: 20px;

/\* #eastpack #cheeta #p: */
font-family: Montserrat-Light;
font-size: 12px;
color: #E53527;
line-height: 20px;

/\* TITLE: */
font-family: Montserrat-Light;
font-size: 20px;
color: #E53527;

/\* image: */
height: 320px;
width: 320px;

/\* thumbnails: */
height: 65px;
width: 65px;

I'll send you all the icons and on the comment section I will give you more details on how the tabs should be adjusted.

**Comment by esperancaJS** [comment]
what about the close button ?

I like the image previews :)

**Comment by mariacovasgrilo** [comment]
We weren't using the close button anymore, since it's kinda intuitive that you just need to click outside the box... but I can make a quick version with the close button. brb

**Comment by mariacovasgrilo** [comment]
![itempopup_closebutton](https://cloud.githubusercontent.com/assets/10408369/7411464/22fcb58e-ef30-11e4-8ccd-0b0b30d1e209.png)

I personally prefer the layout without the close button, but I feel like we should user test it before we compromise with that solution. Until then, we have this one, which works.

**Comment by mariacovasgrilo** [comment]
This is solving part of the issue on #106

**Comment by esperancaJS** [comment]
this are just premature opinions since I have no idea what you are planning for buttons in other places..

#### I have a feeling that this button would go better bellow the item name.

Why? (by order of importance)
- for stores, markets, lists and pages this is probably where the button will go and you know how I love consistency
- like this it seems like only the images will be edited

#### And I have another feeling that the button should be just text

Why? 
- same reasons as above
- text is easier for scaling, we might need new buttons in the future that are hard to symbolize by icons

**Comment by esperancaJS** [comment]
also I'm not feeling love from using a primary color for the item name and price since everywhere else we use that color is for clickable or selectable things and in this case it doesn't serve any interactable purpose.
