### ISSUE TITLE
titles and descriptions in lists, pages and homes

### ISSUE THREAD

**Issue by esperancaJS** [merkatsu/website#44]
this is very important for SEO but also for owners to communicate their page's objectives

**Comment by esperancaJS** [comment]
Since thinking where to insert this elements might lead to restructuring base elements of the website it might be good to have in mind other elements that will be needed:
- stats (in pages might be a simple 'time to read' in lists and homes can be a bunch of diferent numbers)
- store or market diferentiation/icon/something

**Comment by mariacovasgrilo** [comment]
So basically you want every page, every list, and every homepage of shops and markets to have a title and a description.

I understand this is important for pages and lists, but why homes? You only need a description for the homes right? Because the title is already there...

Also, this is going to take some time to do, wouldn't it be better to focus on the ux/ui problems we have right now, solve them, and then go into this?

**Comment by esperancaJS** [comment]
Since this might change base elements it is a high priority.

Yes, homes already have the title there, I would not repeat it, but it's up to you.

**Comment by mariacovasgrilo** [comment]
okay, so that's my number one priority today, and then I'll move down the list.

**Comment by mariacovasgrilo** [comment]
Here is my solution for the Home description solution:

![header-open](https://cloud.githubusercontent.com/assets/10408369/7181213/9daca5be-e440-11e4-8aba-a57ef4e4221f.png)

![header-sidebar-open](https://cloud.githubusercontent.com/assets/10408369/7181278/48e80afe-e441-11e4-937c-5e99e9788e13.png)

/\* Simples Loja: */
font-family: Montserrat-Light;
font-size: 40px;
color: #302B2F;
line-height: 48px;
margin-top: 38px;

/\* FUKKBOYS AND PEOPLE : */
font-family: Montserrat-Regular;
font-size: 12px;
color: #302B2F;
letter-spacing: 0.75px;
line-height: 14px;
text-transform: uppercase;
margin-bottom: 22px;

/\* ACCESSORIES, CLOTHING, ETC: */
font-family: Montserrat-Regular;
font-size: 12px;
color: #302B2F;
letter-spacing: 0.75px;
line-height: 14px;
text-transform: uppercase;
margin-bottom: 22px;

/\* Line: */
margin-top: 4px;
border: 1px solid #302B2F;

/\* CART, EN, MENU: */
font-family: Montserrat-Regular;
font-size: 12px;
color: #E53527;
letter-spacing: 0.74px;
line-height: 14px;
text-transform: uppercase;

/\* header background rectangle: */
width: 100%;
height: 127px;
background: #F5F5F5;
box-shadow: 0px 0px 13px 0px rgba(0,0,0,0.11);

Distance between last menu link on the right and sidebar when open is of 30px. They should never move.

I will send all the icons in the svg format so that they can be transformed into font or however you feel like it's the best way to implement them.

**Comment by esperancaJS** [comment]
OMG YES!

**Comment by esperancaJS** [comment]
the dropdown menu items stay the same for now ?
and in case of more menu items than this they will scale up, right ?

**Comment by mariacovasgrilo** [comment]
yes, they stay the same, they should just change the typeface size to a smaller one, to 12.
What do you mean by scaling up? Going up one line, or?

**Comment by esperancaJS** [comment]
yes, line up

**Comment by mariacovasgrilo** [comment]
yes, I think that is the right solution. maybe I should create that case already

**Comment by mariacovasgrilo** [comment]
![screen shot 2015-04-16 at 16 24 53](https://cloud.githubusercontent.com/assets/10408369/7184479/61a033d2-e455-11e4-8ea1-0323a6222d57.png)

/\* Title: */
font-family: Montserrat-Light;
font-size: 26px;
color: #302B2F;
margin-top: 30px;

/\* Description: */
font-family: Montserrat-Light;
font-size: 13px;
color: #302B2F;
margin-bottom: 30px

![screen shot 2015-04-16 at 16 28 09](https://cloud.githubusercontent.com/assets/10408369/7184527/a97fdf2c-e455-11e4-9970-db49aa218f4b.png)

distance between top red line and bottom red line: 46px.
