### ISSUE TITLE
Initial experience & store/market home

### ISSUE THREAD

**Issue by esperancaJS** [merkatsu/website#76]
These two problems are greatly important and their solution might be connected:
- Should the stores/markets home be a page(note) or a list(collection) or should the users have the choice ?
- How should a user trying out the platform for the first time be guided ?

**Comment by esperancaJS** [comment]
Possible solution:
- This initial home is a page but can be switched to a list later if the user feels like it's more appropriate
- The initial page(note) comes with some initial guiding steps:
  - `visit your first list` on the first list(collection) the first item should be a big button that reads:  `add your first item` or `create your first item` in case of market or store
  -  `edit your business model` or `edit your shipping costs` in case of market or store
  - `invite friends to help you manage this store/market``
  - `edit who can add items to this market's lists(collections)` only if market
  - `add bank info` and receive all profits directly in it
  - `edit the main menu`
  - `edit this page` here we can suggest the user to start deleting items that he has completed, to add images, to make lists,...

**Comment by Ruivilela** [comment]
At this moment merkatsu has no purpose. Just random features on a website that you don't really understand how they work together. I am not saying with this that you should have long tutorial explain what everything does. That is kind of not intuitive and people are not that stupid. What I mean by purpose is to understand what you want to do with merkatsu, what is the purpose of being on merkatsu what do you expect users to do. 

Every actions must have a reaction. At the moment that is not happening. The user arrives to the website, doesn't know about anything and just clicks a random button. That first button that the user clicks doesn't need to have an explanation of what it does. It needs to have a reaction, because people learn by experience. 

It is the same as playing super mario bros. for the first time. You really don't need tutorials to know what the buttons do, so you click them randomly. You know if you click on "A" he jumps because you see mario jumping. You click on the arrows and you understand that those are the directions that mario goes. You really don't know if the turtles are enemies but by going through them you die, so the next time you see them you surely avoid them.  As you can see on the first mario, there is really no explanation what you can do or can't with mario. But you learn quite quickly because for every actions there is an evident reaction. 

In my opinion focus on one important aspect and be fucking good at it. Make it  mario-like intuitive no tutorials, no bullshit. Make it clear what the result of each actions is. After that you can focus on more features, because everything will come together. 

If you want some reading on mario's game design: 
http://www.1up.com/features/learning-level-design-mario

This a funny video on game design
https://www.youtube.com/watch?v=8FpigqfcvlM

P.S: I'm talking a lot about game design because most of these principles are really intuitive, beside the fact that you can use them , you should use them.

**Comment by esperancaJS** [comment]
#### Possible solution 2
1. the user gets to the create store/market page (somehow)
   - on the main page: a mini welcome/tutorial that can't be edited
   - on the side page: he will be able to only edit the name, description and cover of the market/store
2. the user creates the store/market and is redirected to it
   - on the main page: a page(note) that can be edited with some tips, like the ones I mentioned in the first issue
   - on the side page: he now has all the store/market editing options

notes: 
- these 2 welcome notes(pages) would be editable by any merkatsu admin at any time
- the home can also be chosen by the user to be a note(page) or a collection(list) with this solution

**Comment by djtanuzzo** [comment]
Here is how I think it should go:

1 - When you click on the "create store" button in the sidebar it should prompt the store name (required), the store logo (optional) and the store banner (optional).
2 - The store should be created with 2 pre-existing pages, of which one is set as the store's home page. Page 1 should be a list of items, that starts with 3 example items, this page should be set as the store's home page. Page 2 should be an "about" page, that starts with a pre-written text.
3 - The two pages described above should also be automatically be set to be part of the store menu, making a clear connection between pages and navigation for the user.

The best thing would be that once the user has created the store, after he has input the basic data (name, logo, banner), a simple tutorial pops up, which takes the user through what each page is, how to create items, and how to create new pages.

**Comment by esperancaJS** [comment]
answer to @djtanuzzo (numbers correspond)
1 - so it's a good idea to have an intro note on the 'main' correct?
2 - which should the user be redirected to ? the home list and make it welcoming to also add new items, or to the about where we leave some tips?

also about choosing the home at a later time and allowing it to be lists or notes(pages). I'm tempted to allow this.

**Comment by djtanuzzo** [comment]
1 - What do you mean with "intro note" and what is the "main"?
2 - The user should be redirected to the list page (which is automatically set as the home page), and then an automated tutorial should start that takes the user through each step of the way. Something like the facebook tutorials for starting a new page would be best, but else a popup text/video tutorial could work too.

I think the user should definitely be allowed to select his own home page.

**Comment by esperancaJS** [comment]
1- ![](https://cloud.githubusercontent.com/assets/10408369/6998172/58b27a16-dbcf-11e4-8713-59e36ba6bb30.png)
lol not the best image, but main is the white space

thanks @djtanuzzo

**Comment by djtanuzzo** [comment]
I think that any welcome/tutorial messages should come as pop-up windows, and not as part of the main pages. The main pages should only contain information that are real examples of how the store looks like once it is fully operational. This is why I think there should be 3 items in the automatic item list, and there should be a realistic "about" text in the about page.

**Comment by esperancaJS** [comment]
hum makes sense! so when the user clicks 'create store' it should go to a blank store with that pop up open? should he be able to close the pop up or should we demand that he adds a store name first?

**Comment by djtanuzzo** [comment]
The way I see it this is how it should go, step by step:
- User clicks the "create store" button
- A popup shows up prompting for the store name, logo and banner (name is mandatory, logo and banner are optional)
- User clicks the "create store button"
- The popup closes and the user is redirected to the pre-made store homepage, which is a list of items (3 sample items are already inside)

By following this procedure the user understands that his home page is a page with items, and he already has a few sample items to look at to give him a better idea of what his store is like. At the same time by having the "about" page already created, the user can immediately see that he has a menu and where it is. Once he clicks on it he is sent to the about page, which is already filled with text so he has a better idea of what his about page is going to look like.

**Comment by Ruivilela** [comment]
I think that would work nice, squarespace does the pop up of thing too. It works nice because it gives you a sense of action that compels you to do it. As for the information, name is mandatory . The logo and banner even appearing should be something taken into consideration. 

If people put the image, since it's their first time on the website they don't really know where it will be. This may lead into inserting an image in the wrong place, or with the wrong proportion, so they will need to put the image again. So it's really likely that they will have to do things twice or "thrice". 

By not giving the option to put the image right away, you are giving the chance to people see were it will be. So when they upload it, it's more likely that they do it right at first attempt. This way no need for extra steps. 

As for the example thingy, it's nice. Squarespace kinda does it like that. But they do it in an annoying way, they ask "do you want to remove the example and create your own product?" - Of course I want that's an unnecessary step. So if you do the example thing just make the example disappear when people  insert a product. 

I could kinda understand it the first time I did a page, just to make sure i know that i'm editing that specific area and not another. But it does that every fucking time.

**Comment by djtanuzzo** [comment]
I don't think that putting the image is an issue, as long as it is shown well. For example you can have the logo and the banner areas highlighted, or even better we could start each page with a sample logo and banner. The logo could be just a random smiley and the banner could be just a random solid color.

**Comment by JonnyBGod** [comment]
Hum...

I think that should work for now. But I believe it is very important to have highly customizable store pages.

I really think this is critical.
You could have some kind of default list for items that could be the backup for either "no costume page exists" or if (custom page) then it would be used as a "back page" where viewers could go for "standard" design.

This way you would give that chance for individuality for the stores and at the same time have a backup for guys like me that prefer everything clear and standard. (its a "my brain doesn't cope with chaos" problem)

**Comment by djtanuzzo** [comment]
I am not sure I understand what you are saying. Do you mean that the user should have the option to start with a blank store? I think that would be a good option for people that have already opened a store and are now opening their second store, since by then they have already learned the system.

**Comment by JonnyBGod** [comment]
Sorry it was late, I mean that I think we need:
- An easy way to bootstrap simple store front pages based on templates;
- A way to fully customize the page (create new templates; template store, ...)
- A "standard" list of products.
- A customizable list of products.

The standard list of products should always be available even if the store has its own customized list.
The customized list should become the default view for products but the "standard" list should still be available.

**Comment by esperancaJS** [comment]
you mean organizational templates, not design templates, right ?

**Comment by JonnyBGod** [comment]
I mean both.

**Comment by esperancaJS** [comment]
me and @djtanuzzo have talked about organizational templates (#27). It's something I feel that has great potential.
But for beta launch we will likely have to do without

**Comment by JonnyBGod** [comment]
I mean that if you dont have fully customizable pages you would better off not having store pages.

Amazon does not have store pages and opt for one standard platform for sales.
I think it would be nice to have store pages. This way you could bring stores to fully manage their business though merkatsu.

And yes, all this is not needed for beta 1. But should be considered for future versions.
