### ISSUE TITLE
Purpose

### ISSUE THREAD

**Issue by Ruivilela** [merkatsu/website#77]
At this moment merkatsu has no purpose. Just random features on a website that you don't really understand how they work together. I am not saying with this that you should have long tutorial explain what everything does. That is kind of not intuitive and people are not that stupid. What I mean by purpose is to understand what you want to do with merkatsu, what is the purpose of being on merkatsu what do you expect users to do.

Every actions must have a reaction. At the moment that is not happening. The user arrives to the website, doesn't know about anything and just clicks a random button. That first button that the user clicks doesn't need to have an explanation of what it does. It needs to have a reaction, because people learn by experience.

It is the same as playing super mario bros. for the first time. You really don't need tutorials to know what the buttons do, so you click them randomly. You know if you click on "A" he jumps because you see mario jumping. You click on the arrows and you understand that those are the directions that mario goes. You really don't know if the turtles are enemies but by going through them you die, so the next time you see them you surely avoid them. As you can see on the first mario, there is really no explanation what you can do or can't with mario. But you learn quite quickly because for every actions there is an evident reaction.

In my opinion focus on one important aspect and be fucking good at it. Make it mario-like intuitive no tutorials, no bullshit. Make it clear what the result of each actions is. After that you can focus on more features, because everything will come together.

If you want some reading on mario's game design: 
http://www.1up.com/features/learning-level-design-mario

This a funny video on game design
https://www.youtube.com/watch?v=8FpigqfcvlM

P.S: I'm talking a lot about game design because most of these principles are really intuitive, beside the fact that you can use them , you should use them.

**Comment by esperancaJS** [comment]
Hahahah. Ok Rui I'll try out mega man! Really funny video. 
I guess what you meam by purpose might be something we notice in mega man. The main objective is introduced by that boss that shows up and you can't beat and then you spend the whole game trying to reach him and evolving to the challenge. 
Would be great if we could give the store the experience of selling an item or the market the experience of helping a store sell an item as early as possible to show the user a glimpse of the objective ASAP. 
Very enlightening!

**Comment by djtanuzzo** [comment]
I think that we should NOT try and fit all sort of design principles in a project that is unrelated to those principles. The way games tutorialize their first level is great, but games are not an online marketplace. Same goes for how facebook creates a cycle of user interactions to get them hooked, we cannot emulate that because merkatsu is not that sort of platform.

An online marketplace is not a video game, nor is it a social media platform. If you want to search for design hooks that you can borrow from other systems I suggest taking a look at things such as Amazon and eBay, or hell even Pinterest. If we really want to try and gamify merkatsu to try and incentivize certain behaviors, then we could look into having a from of achievement system, however that might be regarded as an annoyance by some users.

**Comment by esperancaJS** [comment]
It is.
So far I like your philosophy @djtanuzzo of quick small accomplishments, such as demanding only for a name to create a store.
But there are always neuron connections that can be created by learning from unrelated projects that can lead to new ideas.. anyways I'm closing this one then
