### ISSUE TITLE
Design Logic

### ISSUE THREAD

**Issue by Ruivilela** [merkatsu/website#79]
You are on the web and for some reason you land on merkatsu....
- First Questions 

What can you do? (client side)

What do we want them to do? (merkatsu dev's) 

So to answer the client side question it's quite easy. Basically what you can do, is limited to the number of buttons there are. Since you are not giving them any instructions. People will click what looks more like a button. Also changing the text to something more appealing, not giving instructions like. But instead giving you the feel what you can do with merkatsu. It's basically setting the rules of what is possible with merkatsu. So this will lead to the second question.   

As for the "merkatsu side" question, it is not as easy. It really depends of what you want to focus on first. And what is important and what brings value to the table:
- Are collections important? Are markets important? Are stores? Or something else that we are missing, 

So let's think a few seconds and stop. Let's face it these three questions are impossible to answer. You can think and try to answer these questions with pure logic. But people aren't really logic, well maybe they are, they are just not mine or your logic. Testing is always good when it's time efficient. So this is my suggestion for a first test. 

1st - Collections

In this first test we want to know if people are into curating products, and earning a margin out of it. For this simple test what is really needed is a page. 

Header - people insert name of their curated list

right side - people insert 
                - Name of the product
                - Image 
                - Link to the store with that product 

On the left side the products appear, and if people click on the product of the list they will be redirected to website with the product. And they'll earn their share by referral. 

For the sake of simplicity (since it's just a test), limit the products to a maximum of 20 items, to guarantee quality of the curations. Limited the website to existing referral system, this way you don't need to create your own system. Amazon can be a good website. Also one page website would be great, just login & insert products. 

The metrics I purpose for this test
- Registration
- nº of referral (Facebook shares, etc… ) 
- Successful referrals

It is just to test if people are willing to create and share. If we can prove people share stuff they curate. We are closer to prove the main function of the market which is the promotion aspect. 

Fail test

If the test fails, it doesn't prove that markets are useless, it may just give us some insight of how markets should work. For example if people share but no sales are made, at some point they are going to get frustrated and stop using the service. So maybe the market aspect should be target to companies who work as middle man. Since they can have both the store and the market. 

So what do you think?

**Comment by esperancaJS** [comment]
This test will happen in merkatsu itself soon enough since we already have enough features implemented to test the initial aspects of the idea, the only missing peace of the puzzle is making it obvious to use now. 

##### As to answer your main question `Are collections important? Are markets important? Are stores?` by which I think you mean `is the combination of all these important?`

We will never know for sure until the idea proves itself. I feel that this is the kind of idea that requires some faith since the only way to test if it is needed is by doing it and making it better until it finally works.
But I can tell you why I strongly feel like it will:
1. the massive value of the few online marketplaces that currently exist
2. the time it takes to build an online marketplace is still very long reducing drastically the amount of people that give life to their marketplace ideas
3. even if someone builds one of these they will be isolated and full of problems related with UI and programming to weigh them down
4. We already have competitors receiving investment

Maybe to further clarify the market value:  [some relatated businesses](https://docs.google.com/document/d/1r8ZQTDUUfk-uA_klQR2Sq3MA-MvEkGOCMK0KjDrVxhw/edit) and [some of their pricings](https://docs.google.com/spreadsheets/d/1oWRSZ656bDw4Wc1uGQtrbTpjHDXc0crfP1kZ1dqe_qM/edit?usp=sharing)

**Comment by esperancaJS** [comment]
I'm closing this now since creating a new platform is too time consuming. And the problem now remains: `understanding the current one`
