### ISSUE TITLE
Banners change position when using different screen sizes

### ISSUE THREAD

**Issue by djtanuzzo** [merkatsu/website#88]
If you change the size of your screen a different part of your banner is shown. This is a problem because if you intend one part of your banner to be the focus and someone has a different size of screen, then your banner ends up looking like crap.

For example in the image below the top part is the banner how I intended it to be, and the bottom part is what it looks like when you use a smaller screen. The problem is not the re-sizing of the banner, but the re-positioning of the focus.

![mkts3](https://cloud.githubusercontent.com/assets/10848233/7159549/e1d1076a-e37a-11e4-9d23-b0815f543e54.png)

**Comment by djtanuzzo** [comment]
In my opinion we should have the users upload and be able to crop their banners in the correct merkatsu dimensions which remain the same no matter what size of a screen you have.

For example it could work like this: when you upload the image you are taken to a screen where you see the image and there is a small window with the correct proportions. You can re-size and move the window, but you cannot alter the proportions. When you click on crop the final position of the window is kept.

The below picture illustrates what I mean:

![mrkts9](https://cloud.githubusercontent.com/assets/10848233/7159699/edcb2f54-e37b-11e4-830d-cc9ddfb029dc.png)

**Comment by mariacovasgrilo** [comment]
@PedroEsperanca what do you think of this? I think it would make the overall look of shops better. Also, takes me no time to design it.

**Comment by esperancaJS** [comment]
I don't think that adding a new pop up is a final solution.

I was thinking on simply thinking about how to automatically position the cover image in a better way so that it looks similar with all screen sizes. Right now it is in fact not working well.

I suggest we leave this approach to when we are sure that automatic sizing will not work (I'm highly confident that it will dough)

**Comment by mariacovasgrilo** [comment]
Automatic sizing will always be a trap, because maybe it's just not what the user wants, and you are forcing him to have an image editor tool in his computer just for a banner.

I understand that a pop up is always an annoying thing but as of in right now, it's probably the best solution, interface wise.

That, or having (aka finding and implementing) a tool that would allow for the user to move and expand the image ON the page itself. If such a thing exists, it would be awesome.

**Comment by djtanuzzo** [comment]
Maybe there is a difficulty in discussing this because we are talking about 2 types of cropping:
1 - Users cropping their images in an editor on merkasu
2 - Merkatsu cropping the user's images when they are displayed

Nr.1 is something that would be nice to have. Not everyone has an image editor or knows how to use one, and we would offer them a simple solution to have a better looking store.

Nr.2 is where the problem lies. Whenever merkatsu crops the user's image without his control, we are introducing possible errors and frustration. Since stores are the backbone of merkatsu, we have to ensure that people have control over them so that they can confidently join the platform.
